theme: jekyll-theme-minimal

<!DOCTYPE html>
<html>
  <head>
    <title> Erica's Site </title>
  </head>
  <style>
    </style>
    <body>
      <h1> Hello, World! </h1>
      <p> This is a test <br></br> :) </p>
    </body>
</html>
